// DO NOT EDIT: Code generated by "generate-jsdoc-example-tests".
import * as assert from 'assert'
import { pipe } from './pipe'

test('Example 1', () => {
  assert.equal(pipe('1', '2', '3'), undefined)
})

test('Example 2', () => {
  assert.equal(pipe('1'), undefined)
})
