// DO NOT EDIT: Code generated by "generate-jsdoc-example-tests".
import * as assert from 'assert'
import { pipe } from './pipe'

test('./examples/nested/pipe.ts_0', () => {
  assert.equal(pipe('1', '2', '3'), undefined)
})

test('./examples/nested/pipe.ts_1', () => {
  assert.equal(pipe('1'), undefined)
})
