// DO NOT EDIT: Code generated by "generate-jsdoc-example-tests".
import * as assert from 'assert'
import { sum, sub, Duck, formatter } from './sample'
import fs from 'node:fs'
import path, { resolve } from 'node:path'
import './side-effects'

test('Example 1', () => {
  assert.equal(sum(4, 5), 9)
})

test('custom name here', () => {
  assert.equal(sub(2, 1), 1)
})

test('Example 2', () => {
  assert.equal(sub(4, 5), -1)
})

test('sub prop is 12', () => {
  assert.equal(sub.prop, 12)
})

test('class method example', () => {
  const duck = new Duck()
  assert.equal(duck.quack(), 'quack')
})

test('Example 3', () => {
  assert.equal(formatter.formatYear(2022), '2022')
})
