import { readFileSync, writeFileSync } from "fs"
import * as path from "path"
import * as ts from "typescript"
import { wrapTestFunction } from "./funcwrapper"
import { mergeImports, splitImport } from "./import"
import { collectExampleCodes, extractComments, parseTSDoc } from "./parser"
import { print } from "./printer"

export async function generate({ filePath }) {
  const { ext, name, dir } = path.parse(filePath);

  let kind;
  switch (ext.toUpperCase()) {
    case ".TS":
      kind = ts.ScriptKind.TS;
      break;
    case ".TSX":
      kind = ts.ScriptKind.TSX;
      console.log("currently unsupported tsx ", filePath);
      return;
    default:
      console.log("unknown file extension ", filePath);
      return;
  }

  const source = ts.createSourceFile(
    filePath,
    readFileSync(filePath).toString(),
    ts.ScriptTarget.Latest,
    false,
    kind
  );

  const foundComments = extractComments(source);

  if (foundComments.length === 0) {
    console.log(`${filePath} comments not found`);
    return;
  }

  const { imports, testBody } = foundComments
    .map(f => {
      return { docNode: parseTSDoc(f), node: f.compilerNode };
    })
    .map(({ docNode, node }) => {
      return collectExampleCodes(node, source, docNode);
    })
    .flat()
    .map(example => {
      return {
        ...example,
        exampleSource: ts.createSourceFile(
          example.name,
          example.code,
          ts.ScriptTarget.Latest,
          false,
          kind
        )
      };
    })
    .reduce(
      (acc, { source, exampleSource, name }) => {
        const { imports, body } = splitImport(exampleSource);

        const fileName = path.relative(process.cwd(), source.fileName)
        const funcName = name || `./${fileName}_${acc.counter++}`;

        const testBody = wrapTestFunction(funcName, body);
        return {
          ...acc,
          imports: [...acc.imports, ...imports],
          testBody: [...acc.testBody, testBody]
        };
      },
      { imports: [], testBody: [], counter: 0 }
    );

  const mergedImports = mergeImports(imports);

  const ast = ts.factory.updateSourceFile(
    ts.createSourceFile(
      filePath + ".doctest",
      "",
      ts.ScriptTarget.Latest,
      false,
      kind
    ),
    [...mergedImports, ...testBody]
  );

  const header = `// Code generated by "tsdoc-testify"; DO NOT EDIT.\n\n`;

  writeFileSync(`${dir}/${name}.doctest.ts`, header + await print(ast));
}
